// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: example.com/services/services.proto

package services

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestForGetBooks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestForGetBooks) Reset() {
	*x = RequestForGetBooks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForGetBooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForGetBooks) ProtoMessage() {}

func (x *RequestForGetBooks) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForGetBooks.ProtoReflect.Descriptor instead.
func (*RequestForGetBooks) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{0}
}

type RequestForGetBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RequestForGetBook) Reset() {
	*x = RequestForGetBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForGetBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForGetBook) ProtoMessage() {}

func (x *RequestForGetBook) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForGetBook.ProtoReflect.Descriptor instead.
func (*RequestForGetBook) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{1}
}

func (x *RequestForGetBook) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type RequestForAddBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookName   string `protobuf:"bytes,1,opt,name=BookName,proto3" json:"BookName,omitempty"`
	AuthorName string `protobuf:"bytes,2,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
}

func (x *RequestForAddBook) Reset() {
	*x = RequestForAddBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForAddBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForAddBook) ProtoMessage() {}

func (x *RequestForAddBook) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForAddBook.ProtoReflect.Descriptor instead.
func (*RequestForAddBook) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{2}
}

func (x *RequestForAddBook) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *RequestForAddBook) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type RequestForUpdateBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BookName   string `protobuf:"bytes,2,opt,name=BookName,proto3" json:"BookName,omitempty"`
	AuthorName string `protobuf:"bytes,3,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
}

func (x *RequestForUpdateBook) Reset() {
	*x = RequestForUpdateBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForUpdateBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForUpdateBook) ProtoMessage() {}

func (x *RequestForUpdateBook) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForUpdateBook.ProtoReflect.Descriptor instead.
func (*RequestForUpdateBook) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{3}
}

func (x *RequestForUpdateBook) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RequestForUpdateBook) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *RequestForUpdateBook) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type RequestForDeleteBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RequestForDeleteBook) Reset() {
	*x = RequestForDeleteBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForDeleteBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForDeleteBook) ProtoMessage() {}

func (x *RequestForDeleteBook) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForDeleteBook.ProtoReflect.Descriptor instead.
func (*RequestForDeleteBook) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{4}
}

func (x *RequestForDeleteBook) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BookName   string `protobuf:"bytes,2,opt,name=BookName,proto3" json:"BookName,omitempty"`
	AuthorName string `protobuf:"bytes,3,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Response) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *Response) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int64 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_com_services_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_com_services_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_example_com_services_services_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

var File_example_com_services_services_proto protoreflect.FileDescriptor

var file_example_com_services_services_proto_rawDesc = []byte{
	0x0a, 0x23, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x4f, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x46, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x14,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x56, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x22, 0x24, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x32, 0xb9, 0x02, 0x0a, 0x0d, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b,
	0x73, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46,
	0x6f, 0x72, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x1a,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x40, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b,
	0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x46, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x1a, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_com_services_services_proto_rawDescOnce sync.Once
	file_example_com_services_services_proto_rawDescData = file_example_com_services_services_proto_rawDesc
)

func file_example_com_services_services_proto_rawDescGZIP() []byte {
	file_example_com_services_services_proto_rawDescOnce.Do(func() {
		file_example_com_services_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_com_services_services_proto_rawDescData)
	})
	return file_example_com_services_services_proto_rawDescData
}

var file_example_com_services_services_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_example_com_services_services_proto_goTypes = []interface{}{
	(*RequestForGetBooks)(nil),   // 0: proto.RequestForGetBooks
	(*RequestForGetBook)(nil),    // 1: proto.RequestForGetBook
	(*RequestForAddBook)(nil),    // 2: proto.RequestForAddBook
	(*RequestForUpdateBook)(nil), // 3: proto.RequestForUpdateBook
	(*RequestForDeleteBook)(nil), // 4: proto.RequestForDeleteBook
	(*Response)(nil),             // 5: proto.Response
	(*DeleteResponse)(nil),       // 6: proto.DeleteResponse
	(*UpdateResponse)(nil),       // 7: proto.UpdateResponse
}
var file_example_com_services_services_proto_depIdxs = []int32{
	0, // 0: proto.BooksServices.GetBooks:input_type -> proto.RequestForGetBooks
	1, // 1: proto.BooksServices.GetBook:input_type -> proto.RequestForGetBook
	2, // 2: proto.BooksServices.AddBook:input_type -> proto.RequestForAddBook
	3, // 3: proto.BooksServices.UpdateBook:input_type -> proto.RequestForUpdateBook
	4, // 4: proto.BooksServices.DeleteBook:input_type -> proto.RequestForDeleteBook
	5, // 5: proto.BooksServices.GetBooks:output_type -> proto.Response
	5, // 6: proto.BooksServices.GetBook:output_type -> proto.Response
	5, // 7: proto.BooksServices.AddBook:output_type -> proto.Response
	7, // 8: proto.BooksServices.UpdateBook:output_type -> proto.UpdateResponse
	6, // 9: proto.BooksServices.DeleteBook:output_type -> proto.DeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_com_services_services_proto_init() }
func file_example_com_services_services_proto_init() {
	if File_example_com_services_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_com_services_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForGetBooks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_com_services_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForGetBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_com_services_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForAddBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_com_services_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForUpdateBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_com_services_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForDeleteBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_com_services_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_com_services_services_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_com_services_services_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_com_services_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_com_services_services_proto_goTypes,
		DependencyIndexes: file_example_com_services_services_proto_depIdxs,
		MessageInfos:      file_example_com_services_services_proto_msgTypes,
	}.Build()
	File_example_com_services_services_proto = out.File
	file_example_com_services_services_proto_rawDesc = nil
	file_example_com_services_services_proto_goTypes = nil
	file_example_com_services_services_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BooksServicesClient is the client API for BooksServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BooksServicesClient interface {
	GetBooks(ctx context.Context, in *RequestForGetBooks, opts ...grpc.CallOption) (BooksServices_GetBooksClient, error)
	GetBook(ctx context.Context, in *RequestForGetBook, opts ...grpc.CallOption) (*Response, error)
	AddBook(ctx context.Context, in *RequestForAddBook, opts ...grpc.CallOption) (*Response, error)
	UpdateBook(ctx context.Context, in *RequestForUpdateBook, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteBook(ctx context.Context, in *RequestForDeleteBook, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type booksServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewBooksServicesClient(cc grpc.ClientConnInterface) BooksServicesClient {
	return &booksServicesClient{cc}
}

func (c *booksServicesClient) GetBooks(ctx context.Context, in *RequestForGetBooks, opts ...grpc.CallOption) (BooksServices_GetBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BooksServices_serviceDesc.Streams[0], "/proto.BooksServices/GetBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &booksServicesGetBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BooksServices_GetBooksClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type booksServicesGetBooksClient struct {
	grpc.ClientStream
}

func (x *booksServicesGetBooksClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *booksServicesClient) GetBook(ctx context.Context, in *RequestForGetBook, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.BooksServices/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServicesClient) AddBook(ctx context.Context, in *RequestForAddBook, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.BooksServices/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServicesClient) UpdateBook(ctx context.Context, in *RequestForUpdateBook, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.BooksServices/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksServicesClient) DeleteBook(ctx context.Context, in *RequestForDeleteBook, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.BooksServices/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BooksServicesServer is the server API for BooksServices service.
type BooksServicesServer interface {
	GetBooks(*RequestForGetBooks, BooksServices_GetBooksServer) error
	GetBook(context.Context, *RequestForGetBook) (*Response, error)
	AddBook(context.Context, *RequestForAddBook) (*Response, error)
	UpdateBook(context.Context, *RequestForUpdateBook) (*UpdateResponse, error)
	DeleteBook(context.Context, *RequestForDeleteBook) (*DeleteResponse, error)
}

// UnimplementedBooksServicesServer can be embedded to have forward compatible implementations.
type UnimplementedBooksServicesServer struct {
}

func (*UnimplementedBooksServicesServer) GetBooks(*RequestForGetBooks, BooksServices_GetBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBooks not implemented")
}
func (*UnimplementedBooksServicesServer) GetBook(context.Context, *RequestForGetBook) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBooksServicesServer) AddBook(context.Context, *RequestForAddBook) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (*UnimplementedBooksServicesServer) UpdateBook(context.Context, *RequestForUpdateBook) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (*UnimplementedBooksServicesServer) DeleteBook(context.Context, *RequestForDeleteBook) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}

func RegisterBooksServicesServer(s *grpc.Server, srv BooksServicesServer) {
	s.RegisterService(&_BooksServices_serviceDesc, srv)
}

func _BooksServices_GetBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestForGetBooks)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BooksServicesServer).GetBooks(m, &booksServicesGetBooksServer{stream})
}

type BooksServices_GetBooksServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type booksServicesGetBooksServer struct {
	grpc.ServerStream
}

func (x *booksServicesGetBooksServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _BooksServices_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestForGetBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServicesServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BooksServices/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServicesServer).GetBook(ctx, req.(*RequestForGetBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksServices_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestForAddBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServicesServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BooksServices/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServicesServer).AddBook(ctx, req.(*RequestForAddBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksServices_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestForUpdateBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServicesServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BooksServices/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServicesServer).UpdateBook(ctx, req.(*RequestForUpdateBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksServices_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestForDeleteBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServicesServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BooksServices/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServicesServer).DeleteBook(ctx, req.(*RequestForDeleteBook))
	}
	return interceptor(ctx, in, info, handler)
}

var _BooksServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BooksServices",
	HandlerType: (*BooksServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBook",
			Handler:    _BooksServices_GetBook_Handler,
		},
		{
			MethodName: "AddBook",
			Handler:    _BooksServices_AddBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BooksServices_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BooksServices_DeleteBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBooks",
			Handler:       _BooksServices_GetBooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example.com/services/services.proto",
}
